[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "stripe"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Finance/Payment", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-stripe"

[build-options]
observabilityIncluded = true
